### PR TITLE
Document dfr/reduce-+ & dfr/reduce-*

### PR DESCRIPTION
**Pull request by shellandbull**
Documents the methods `reduce-+` and `reduce-*` - cheers to @daslu for pairing with me on this one 🌞

### CODE REVIEW

**Review by cnuernber — APPROVED** [review]
Looks great to me!  Thanks.

**Comment by shellandbull** [comment]
@cnuernber thanks, it's a pleasure meeting you Chris 😄 let me add a few more and mark this as ready for review

**Comment by shellandbull** [comment]
@cnuernber Hello there, this is now ready for a review and merge 😸 I documented all the other functions named like `reduce-`

**Comment by shellandbull** [comment]
🎊 🎊 🎊 🎊  My first Clojure PR is now merged!

**Comment by harold** [comment]
@shellandbull - very cool accomplishment. :clap: 

Here's a similar(-ish) issue, in case that's of interest: https://github.com/techascent/tech.ml.dataset/issues/412

(cc: @daslu)

**Pull request merged**
